
# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
brew brew-cask
cask 0xed
cask animated-gif-quicklook
cask appcleaner
cask atom
cask betterzipql
cask dash
cask epubquicklook
cask filezilla
cask flash
cask genymotion
cask github-desktop
cask google-chrome
cask google-japanese-ime
cask intel-haxm
cask intellij-idea
cask iterm2
cask java
cask karabiner
cask kdiff3
cask kindle
cask macdown
cask mou
cask openemu
cask opera-mail
cask opera
cask owncloud
cask paintbrush
cask pgweb
cask qlcolorcode
cask qlgradle
cask qlimagesize
cask qlmarkdown
cask qlprettypatch
cask qlrest
cask qlstephen
cask qlvideo
cask quicklook-csv
cask quicklook-json
cask silverlight
cask skitch
cask skype
cask slack
cask sourcetree
cask sublime-text
cask suspicious-package
cask the-unarchiver
cask transmission
cask tuxguitar
cask uninstallpkg
cask unpkg
cask vagrant
cask virtualbox
cask vlc
cask vmware-fusion
cask wireshark
cask xquartz
cask xtrafinder
cask yujitach-menumeters

## caskroom/fonts
tap caskroom/fonts
cask font-koruri

## caskroom/versions
tap caskroom/versions
cask firefox-ja
cask java7
cask macvim-kaoriya
cask vivaldi-snapshot

## homebrew/boneyard
tap homebrew/boneyard
brew pyenv-pip-rehash

## homebrew/versions
tap homebrew/versions
brew ansible14

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew android-sdk
brew ant
brew apache-spark
brew autoconf
brew automake
brew awscli
brew bash
brew binutils
brew boost
brew brew-gem
brew brew-pip
brew cmake
brew colordiff
brew coreutils
brew ctags
brew curl
brew direnv
brew docker
brew docker-compose
brew docker-machine
brew dos2unix
brew doxygen
brew ec2-api-tools
brew enscript
brew fish
brew flyway
brew freetype
brew gdbm
brew gettext
brew git
brew gmp
brew gnu-sed
brew go
brew gradle
brew groovy
brew htop-osx
brew httpie
brew hub
brew icu4c
brew imagemagick
brew intltool
brew ios-sim
brew jenv
brew jpeg
brew jq
brew lame
brew ldns
brew libevent
brew libpng
brew libtiff
brew libtool
brew libyaml
brew lua
brew luajit
brew lzo
brew maven
brew mercurial
brew multitail
brew neon
brew nkf
brew nmap
brew node
brew nodebrew
brew oniguruma
brew openssl
brew ossp-uuid
brew pandoc
brew pcre
brew pigz
brew pkg-config
brew postgresql
brew pstree
brew pv
brew pyenv
brew pyenv-virtualenv
brew pyenv-virtualenvwrapper
brew python
brew rbenv
brew rbenv-bundler
brew rbenv-gemset
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew sbt
brew scala
brew scons
brew sqlite
brew thrift
brew tig
brew tmux
brew typesafe-activator
brew unar
brew vimpager
brew wget
brew xhyve
brew xz
brew zsh
brew zsh-completions
brew zsh-syntax-highlighting

# App Store applications
appstore GarageBand
appstore iMovie
appstore iPhoto
appstore Keynote
appstore Microsoft Remote Desktop
appstore Numbers
appstore Pages
appstore Xcode
